---
# COPY this file to secrets.yml
# Do not provide any real key in this file. No keys should be pushed to Youtube
development:
  API_HOST: http://localhost:9090
  APP_HOST: http://localhost:9000
  SESSION_SECRET: <GENERATED_SECRET>

app_test:
  API_HOST: http://localhost:9090
  APP_HOST: http://localhost:9000

test:
  API_HOST: http://localhost:9090
  APP_HOST: http://localhost:9000
  SESSION_SECRET: <GENERATED_SECRET>

production:
  # - assign DATABASE_URL in production
  API_HOST: http://url.to.api
  APP_HOST: http://url.to.app
  SESSION_SECRET: <GENERATED_SECRET>
